### ISSUE TITLE
Using sessions will break Varnish type caches

### ISSUE THREAD

**Issue by Ipstenu** [sterndata/wp-referrer-modal#3]
Calling ob_start() here - https://github.com/sterndata/wp-referrer-modal/blob/262832170d27c2bcae0c1892957ef3af33969391/sds-wp-modal.php#L43

That could be dangerous on sites with server side caching (see Varnish). Any time you put down new sessions like that, it wipes out the cache :(

Everything else looks fine though!

**Comment by sterndata** [comment]
Would stuffing a string ( $text .= 'more text'; ) be a better solution on a site with Varnish?

**Comment by lucyllewy** [comment]
@Ipstenu I'm curious about this suggestion.. The output-buffer (inside PHP) shouldn't affect a Varnish proxy (outside PHP) which is down-stream in the request path. AFAIK Varnish caches the data from a request *after* PHP has finished with it, so `ob_start` should not affect that. I think you might be confusing `ob_start` with `session_start`, based on the title of this issue, which will set a cookie. Any presence of session-specific cookies WILL prevent Varnish from caching but as I say the output-buffer doesn't set such a cookie...

🤔

/me prepares to be edumacated 'cos I'm confused now that my faith in the output buffer is shaken :-p

**Comment by Ipstenu** [comment]
Nope, they both do it. Which is ridiculous, I know, but any time you put it in footer, I've watched it blast cache away a million times and it drives me up a wall. The other side is if you configured your Varnish server the other way, you always get the cached version of that output buffer, which again defeats the purpose :/ Basically sessions and buffering = bad cache drama.

**Comment by lucyllewy** [comment]
well fooey, that's really sucky :-(

**Comment by sterndata** [comment]
Hmmm... I've got a private plugin I use on at least Dreampress site, so I guess I better fix that one, too.

**Comment by lucyllewy** [comment]
I can't find any mention of this issue via googling extensively other than from yourself, Mika. I'd really like to understand what about `ob_start()` is killing a Varnish cache, and potential work-arounds or fixes that can go upstream to PHP. Is there a PHP bug in their issue tracker I can follow, or reduced test-cases I can try to see the behaviour?

**Comment by Ipstenu** [comment]
It's not a bug, it's everything doing what it's supposed to.

So `add_filter( 'wp_footer', 'sds_wp_referrer_modal_filter' );` means on every page load, the `ob_start` is called at the bottom, which starts the output buffer.

Varnish buffers output by default. Run 'em both and weird things happen. On some Varnish setups, doing this on every page load causes the cache to not process properly. That is, which buffer is going to be hit first? Which is 'right'? Which version gets cached by Varnish?

Though I'm not sure why you're putting it down at all. Plus updating the option on every page load seems a little overkill.
